/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysao;

import mysao.Clubs.NewClub;
import mysao.Clubs.ListClubs;
import mysao.Clubs.Search_A_Club;
import mysao.Events.ListEvents;
import mysao.Events.NewEvent;

/**
 *
 * @author hp
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SearchClubs_jButton = new javax.swing.JButton();
        CreateClub_jButton1 = new javax.swing.JButton();
        ListEvent_jButton = new javax.swing.JButton();
        Exit_jButton = new javax.swing.JButton();
        LogOut_jButton = new javax.swing.JButton();
        CreateEvetn_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Home Menu");

        SearchClubs_jButton.setText("List Clubs");
        SearchClubs_jButton.setToolTipText("");
        SearchClubs_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchClubs_jButtonActionPerformed(evt);
            }
        });

        CreateClub_jButton1.setText("Create Club");
        CreateClub_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateClub_jButton1ActionPerformed(evt);
            }
        });

        ListEvent_jButton.setText("List Events");
        ListEvent_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListEvent_jButtonActionPerformed(evt);
            }
        });

        Exit_jButton.setText("Exit");
        Exit_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_jButtonActionPerformed(evt);
            }
        });

        LogOut_jButton.setText("Log Out");
        LogOut_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_jButtonActionPerformed(evt);
            }
        });

        CreateEvetn_jButton.setText("Create Event");
        CreateEvetn_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateEvetn_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ListEvent_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchClubs_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(CreateClub_jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CreateEvetn_jButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(LogOut_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit_jButton)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchClubs_jButton)
                    .addComponent(CreateClub_jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListEvent_jButton)
                    .addComponent(CreateEvetn_jButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit_jButton)
                    .addComponent(LogOut_jButton))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchClubs_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchClubs_jButtonActionPerformed
        // TODO add your handling code here:
        ListClubs frm = new ListClubs();
        frm.setLocation(getLocation());
        frm.setSize(getSize());
        setVisible(false);
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_SearchClubs_jButtonActionPerformed

    private void CreateClub_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateClub_jButton1ActionPerformed
        // TODO add your handling code here:
        NewClub frm = new NewClub();
        frm.setLocation(getLocation());
        frm.setSize(getSize());
        setVisible(false);
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_CreateClub_jButton1ActionPerformed

    private void ListEvent_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListEvent_jButtonActionPerformed
        // TODO add your handling code here:
        ListEvents frm = new ListEvents();
        frm.setLocation(getLocation());
        frm.setSize(getSize());
        setVisible(false);
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_ListEvent_jButtonActionPerformed

    private void Exit_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_jButtonActionPerformed
        // TODO add your handling code here
        System.exit(0);
    }//GEN-LAST:event_Exit_jButtonActionPerformed

    private void LogOut_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_jButtonActionPerformed
        // TODO add your handling code here:
        LogIn frm = new LogIn();
        frm.setLocation(getLocation());
        frm.setSize(getSize());
        setVisible(false);
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOut_jButtonActionPerformed

    private void CreateEvetn_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateEvetn_jButtonActionPerformed
        // TODO add your handling code here:
        NewEvent frm = new NewEvent();
        frm.setLocation(getLocation());
        frm.setSize(getSize());
        setVisible(false);
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_CreateEvetn_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateClub_jButton1;
    private javax.swing.JButton CreateEvetn_jButton;
    private javax.swing.JButton Exit_jButton;
    private javax.swing.JButton ListEvent_jButton;
    private javax.swing.JButton LogOut_jButton;
    private javax.swing.JButton SearchClubs_jButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
